language: scala
matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
      jdk: oraclejdk8
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: oraclejdk8
    - scala: 2.12.8
      env: PLAY_VERSION=2.6
      jdk: oraclejdk8

notifications:
  email:
    recipients:
    - platform-engineering@digital.hmrc.gov.uk

before_script:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5"
  - "echo 'deb https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org"
  - "sudo service mongod start"
  - "sleep 15" #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - "mongo --version"

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - $HOME/.m2
