language: scala
matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.5
      jdk: oraclejdk8
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: oraclejdk8
    - scala: 2.12.8
      env: PLAY_VERSION=2.6
      jdk: oraclejdk8

notifications:
  email:
    recipients:
    - platform-engineering@digital.hmrc.gov.uk
before_script:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org=2.6.5 mongodb-org-server=2.6.5 mongodb-org-shell=2.6.5 mongodb-org-mongos=2.6.5 mongodb-org-tools=2.6.5"
  - "sleep 15" #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - "mongo --version"
